package com.karoocameracontrol.extension

// Mapping based on OpenGoPro EnumPresetTitle
// Source: https://github.com/gopro/OpenGoPro/blob/main/protobuf/preset_status.proto
object PresetTitle {
    fun getTitle(id: Int): String {
        return when (id) {
            0 -> "Activity"
            1 -> "Standard"
            2 -> "Cinematic"
            3 -> "Photo"
            4 -> "Live Burst"
            5 -> "Burst"
            6 -> "Night"
            7 -> "TimeWarp"
            8 -> "Time Lapse"
            9 -> "Night Lapse"
            10 -> "Video"
            11 -> "Slo-Mo"
            13 -> "Photo"
            14 -> "Panorama"
            16 -> "TimeWarp"
            18 -> "Custom"
            19 -> "Air"
            20 -> "Bike"
            21 -> "Epic"
            22 -> "Indoor"
            23 -> "Motor"
            24 -> "Mounted"
            25 -> "Outdoor"
            26 -> "POV"
            27 -> "Selfie"
            28 -> "Skate"
            29 -> "Snow"
            30 -> "Trail"
            31 -> "Travel"
            32 -> "Water"
            33 -> "Looping"
            34 -> "Stars"
            35 -> "Action"
            36 -> "Follow Cam"
            37 -> "Surf"
            38 -> "City"
            39 -> "Shaky"
            40 -> "Chesty"
            41 -> "Helmet"
            42 -> "Bite"
            43 -> "Custom Cinematic"
            44 -> "Vlog"
            45 -> "FPV"
            46 -> "HDR"
            47 -> "Landscape"
            48 -> "Log"
            49 -> "Custom Slo-Mo"
            50 -> "Tripod"
            58 -> "Basic"
            59 -> "Ultra Slo-Mo"
            60 -> "Standard Endurance"
            61 -> "Activity Endurance"
            62 -> "Cinematic Endurance"
            63 -> "Slo-Mo Endurance"
            64 -> "Stationary 1"
            65 -> "Stationary 2"
            66 -> "Stationary 3"
            67 -> "Stationary 4"
            68 -> "Simple Video"
            69 -> "Simple TimeWarp"
            70 -> "Simple SuperPhoto"
            71 -> "Simple Night Photo"
            72 -> "Simple Video Endurance"
            73 -> "Highest Quality"
            74 -> "Extended Battery"
            75 -> "Longest Battery"
            76 -> "Star Trail"
            77 -> "Light Painting"
            78 -> "Light Trail"
            79 -> "Full Frame"
            82 -> "Standard Quality Video"
            83 -> "Basic Quality Video"
            93 -> "Highest Quality Video"
            99 -> "Easy Standard Profile"
            100 -> "Easy HDR Profile"
            106 -> "Burst Slo-Mo"
            125 -> "4:3 Video"
            126 -> "16:9 Video"
            127 -> "16:9 Slo-Mo"
            131 -> "Time Lapse Video"
            132 -> "Time Lapse Photo"
            133 -> "Night Lapse Video"
            134 -> "Night Lapse Photo"
            else -> "Preset $id"
        }
    }
}
